blog/urls.py
from django.urls import path
from .import views

app_name="blog"

urlpatterns=[
    path("", views.index, name="index"),
    path("post/<str:slug>", views.detail, name="detail"),
    path("new_somethingurl", views.new_url_view, name="new_url_id"),
    path("old_url", views.old_url_redirect, name="old_url"),
    path("contact", views.contact, name="contact"),
    path("about", views.about, name="about"),
    path("register", views.register, name="register"),
    path("login", views.login, name="login"),
    path("dashboard", views.dashboard, name="dashboard"),
    path("logout", views.logout, name="logout"),
    path("forgot_password", views.forgot_password, name="forgot_password"),
    #base64string and tokenvalue
    path("reset_password/<uidb64>/<token>", views.reset_password, name="reset_password" ),
    path("new_post", views.new_post, name="new_post"),
    path("edit_post/<int:post_id>",views.edit_post, name="edit_post"),
    path("delete_post/<int:post_id>",views.delete_post, name="delete_post"),
    path("publish_post/<int:post_id>", views.publish_post, name="publish_post"),



]

myapp/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings


handler400 = 'myapp.views.custompage'
urlpatterns = [
    path("", include("blog.urls")),
    path('admin/', admin.site.urls),
#its used to add media root to the img
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/models.py
from django.db import models
#to import for slug
from django.utils.text import slugify
from django.contrib.auth.models import User

#category model  
class Category(models.Model):
    name = models.CharField(max_length=100)
   
    def __str__(self):
        return self.name

# Create your models here.
class Post(models.Model):
    title = models.CharField(max_length=100)
    content = models.TextField()
    #ImageField is used to upload the image, upload_to = where the images want to store"
    img_url = models.ImageField(null=True, upload_to="posts/images")
    created_at = models.DateTimeField(auto_now_add=True)
    slug = models.SlugField(unique=True)
    #to add many to one category
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    #add the user for the created post in dashboard so getting data from database
    user = models.ForeignKey(User, on_delete=models.CASCADE, null=True)
    #if user added a new post if they want to publish it then only it want to reflect in page
    #its an boolean field should defaultly be false if they give publish then only it want to true and reflect
    is_published = models.BooleanField(default=False)

#to generate slug
    def save(self, *args, **kwargs):
        self.slug = slugify(self.title)
        super().save(*args, **kwargs)
    #returns a special descriptor object which allows direct access to getter, setter, and deleter methods
    @property
    def formatted_img_url(self):
        url = self.img_url if self.img_url.__str__().startswith(('http://','https://')) else self.img_url.url
        return url


    def __str__(self):
        return self.title

class AboutUs(models.Model):
    content = models.TextField()

blog/views.py
from django.shortcuts import render, redirect,get_object_or_404
from django.http import HttpResponse
from django.urls import reverse
import logging
#to import for models
from .models import Category, Post, AboutUs
#import for exception handling
from django.http import Http404 
#to import for pagination
from django.core.paginator import Paginator
 #importing forms module from django
from .forms import ContactForm, ForgotPasswordForm, PostForm, RegisterForm, LoginForm, ResetPasswordForm
#message module
from django.contrib import messages
#to import authenticate and login as auth_login
from django.contrib.auth import authenticate, login as auth_login, logout as auth_logout
#import forms
from blog import forms
#import user
from django.contrib.auth.models import User
#token generator
from django.contrib.auth.tokens import default_token_generator
#import urlsafe base64 encode- trying to pass a user ID (primary key) to url as base 64 encoded
from django.utils.http import urlsafe_base64_encode, urlsafe_base64_decode
#import force_bytes() will convert the given int to str and then convert that str to bytes.
from django.utils.encoding import force_bytes
#import Check if contrib.sites is installed and return either the current Site object or a RequestSite object based on the request.
from django.contrib.sites.shortcuts import get_current_site
#import Load a template and render it with a context. Return a string.
from django.template.loader import render_to_string
#sending an Email
from django.core.mail import send_mail
#import decorators for loginrequired
from django.contrib.auth.decorators import login_required, permission_required
#import models groups
from django.contrib.auth.models import Group


# Create your views here.
#posts=[
 #       {"id":1, "title":"Post 1", "content":"This is the first post"},
 #       {"id":2, "title":"Post 2", "content":"This is the second post"},
  #      {"id":3, "title":"Post 3", "content":"This is the third post"},
   #     {"id":4, "title":"Post 4", "content":"This is the fourth post"},
   # ]

def index(request):
    #variable interpolation
    blog_title="Latest Posts"
    #getting data from all post model
    #all_posts = Post.objects.all()
    #getting data from post model using filter
    all_posts = Post.objects.filter(is_published=True)
    #pagination
    #paginator to assign all posts and number of posts to be displayed
    paginator = Paginator(all_posts, 5)
    #getting page number from request
    page_number = request.GET.get('page')
    #getting posts from paginator
    page_obj = paginator.get_page(page_number)

    return render(request, "blog/index.html",  {'blog_title': blog_title , 'page_obj': page_obj})#variable interpolation

def detail(request, slug):
    if request.user and not request.user.has_perm('blog.view_post'):
        messages.error(request,'You have no permission to view any post!')
        return redirect('blog:index')

    #static data
    #post = next((item for item in posts if item["id"] == int(post_id)), None)
    #handling exception
    try:
        #getting data from post model using id from database
        #post = Post.objects.get(pk=post_id)

        #getting data from post model using slug from database
        post = Post.objects.get(slug=slug)
        #getting related posts
        related_post = Post.objects.filter(category = post.category).exclude(pk=post.id)
    except Post.DoesNotExist:
        raise Http404("Post Does Not Exist")
    #logger = logging.getLogger("TESTING")
    #logger.debug(f"post variable is {post}")
    return render(request,"blog/detail.html", {'post':post , 'related_posts':related_post})

def old_url_redirect(request):
    return redirect(reverse("blog:new_url_id"))

def new_url_view(request):
    return HttpResponse("This is the new URL")

def contact(request):
    #getting data from the form
    #if request == submit then get the data from the form
    if request.method == "POST":
        form = ContactForm(request.POST)
        name = request.POST.get('name')
        email = request.POST.get('email')
        message = request.POST.get('message')
        #logging
        logger = logging.getLogger("TESTING")
        #logger.debug(f"post data is {name} {email} {message}")
        #if form is valid then get the data from the form
        if form.is_valid():
            logger.debug(f"post data is {form.cleaned_data['name']} {form.cleaned_data['email']} {form.cleaned_data['message']}")
            #success message
            success_message = "Form submitted successfully"
            return render(request,"blog/contact.html",{'form':form, 'success_message':success_message})
        else:
            logger.debug("Form is invalid")
            #error message
        return render(request,"blog/contact.html",{'form':form, 'name':name, 'email':email, 'message':message})
    return render(request,"blog/contact.html")

def about(request):
    #getting data from the about us model in admin page as a dynamic content
    about_content=AboutUs.objects.first().content
    return render(request, "blog/about.html",{'about_content':about_content})

def register(request):
    form = RegisterForm()
    if request.method == "POST":
        form = RegisterForm(request.POST)
        if form.is_valid():
            #while saving user data it will commit false 
            user = form.save(commit = False) #user data creation
            #set_password method is used to hash the password(inbuilt method) -> getting data using cleaned_data method and get the value of password
            user.set_password(form.cleaned_data["password"])
            #save the data in database
            user.save()
            #get or create from the name Readers
            readers_group,created = Group.objects.get_or_create(name="Readers")
            #users will get add under the readers group
            user.groups.add(readers_group)
            #messages.success method is used to display the message
            messages.success(request,"Registration Successful. You can login!!")  
            return redirect("blog:login")       
    return render(request, "blog/register.html", {'form':form})

def login(request):
    form = LoginForm()
    if request.method == "POST":
        #loginform
        form = LoginForm(request.POST)
        #if form is valid
        if form.is_valid():
            #get data from cleaned_data dictionary
            username=form.cleaned_data["username"]
            password=form.cleaned_data["password"]
            # it authenticate from the database
            user = authenticate(username=username, password=password)
            #if user values is not none then
            if user is not None:
                #login request of the user
                auth_login(request, user)
                #redirect to the dashboard page
                return redirect("blog:dashboard")
                #it prints the value
                print("Login Successfully")
    return render(request, "blog/login.html", {'form':form})

def dashboard(request):
    blog_title ="My Posts"
     #getting data from all post model
    all_posts=Post.objects.filter(user=request.user)
    #paginator to assign all posts and number of posts to be displayed
    paginator = Paginator(all_posts, 5)
    #getting page number from request
    page_number = request.GET.get('page')
    #getting posts from paginator
    page_obj = paginator.get_page(page_number)
    return render(request, 'blog/dashboard.html',{"blog_title":blog_title, 'page_obj':page_obj})

def logout(request):
    auth_logout(request)
    return redirect("blog:index")

def forgot_password(request):
    form = ForgotPasswordForm()
    if request.method == 'POST':
        form = ForgotPasswordForm(request.POST)
        if form.is_valid():
            email = form.cleaned_data['email']
            user = User.objects.get(email=email)
            #send email to reset password
            #used to create a default token for the user
            token = default_token_generator.make_token(user)
            #urlsafe_base64 - Encode a bytestring to a base64 string for use in URLs
            #forcebyte-convert string into the bytes using primary key as per the user
            uid = urlsafe_base64_encode(force_bytes(user.pk))
            #get current site data like http://127.0.0.1:8000/
            current_site = get_current_site(request)
            #to get the data from template and display in domain http://127.0.0.1:8000/
            domain = current_site.domain
            subject = "Reset Password Requested"
            #get the message from template
            #render to string - convert to string
            message = render_to_string('blog/reset_password_email.html',{
                'domain': domain,
                #base 64
                'uid': uid,
                #primary token id
                'token': token
            })
            #sending an email(subject, message, from-mail,recipent list whom want to receive email)
            send_mail(subject, message, 'noreply@gmail.com', [email])
            messages.success(request,"Email has been sent")

    return render(request,"blog/forgot_password.html", {'form':form})


def reset_password(request, uidb64, token):
    form = ResetPasswordForm()
     #if request == submit then get the data from the form
    if request.method == 'POST':
        #form
        form = ResetPasswordForm(request.POST)
        if form.is_valid():
            new_password = form.cleaned_data['new_password']
            try:
                uid = urlsafe_base64_decode(uidb64)
                user = User.objects.get(pk=uid)
            except(TypeError, ValueError, OverflowError, User.DoesNotExist):
                user = None


blog/templates/blog/about.html
{% extends 'blog/base.html' %}

{% block content %}
    <div class="container-fluid ">
        <h3>About Us</h3>
        <div class="d-flex gap-3 justify-content-center mt-5">
            <img src="https://picsum.photos/300/300" alt="">
            <div class="content">
               {{about_content}}
            </div>
            
        </div>
    </div>
{% endblock %}

blog/templates/blog/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{{blog_title | default:"Document"}}</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'blog/style.css' %}">
</head>
<body> 
    <!-- Header -->
    {% include 'blog/includes/header.html' %}
    
    <!-- Dynamic content -->
    {% block content %} 
    {% endblock %}

    <!-- Footer -->
    {% include 'blog/includes/footer.html' %}
   
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
</body>
</html>

blog/templates/blog/dashboard.html
{% extends 'blog/base.html'%}

{%block content %}
    <div class="container-fluid ">
        <div class="row">
          <div class="col-6">
              <h3> Hi, {{user.username}}.</h3>
          </div>
          <div class="col d-flex justify-content-end">
              <div>
                  <h2>Your Groups:</h2>
                  <ul>
                    <!--fetch the all user group details in store in group-->
                    {% for group in user.groups.all %}
                    <!--it will print the group name of the user here-->
                      <li>{{group.name}}</li>
                      <!--text is displayed if the given array is empty or could not be found-->
                      {% empty %}
                      <li>You are not a member of any groups.</li>
                    {% endfor %}
                    </ul>
              </div>
          </div>
        </div>
        <!--included post updated msg -->
        <div class="row d-flex justify-content-center">
          <div class="col-6">
              {% include 'blog/includes/errors.html'%}
          </div>
        </div>
        <div class="row">
          <h2 class="mt-3">{{blog_title}}</h2>
          <!--if the permission perms variable is there in blog code name ->add_post then they can view new post button like only authors and editors not readers-->
          {%if perms.blog.add_post %}          
          <div class="d-flex justify-content-center">
              <a href="{% url 'blog:new_post'%}" class="btn btn-success">New Post</a>
          </div>
          {% endif %}
        </div>
        <div class="row m-3">
            {% if page_obj %}
            <!---for through the paginator-->
                {% for post in page_obj %}
                    <div class="col-4 mb-4">
                        <div class="card">
                            <div class="card-body">
                                <div class="row">
                                    <div class="col-md-4">
                                        <!--.url method is used to add the media in the image prefix so that we can view the new post image
                                        as well as for short naming images we use img and in the long img url its not needed-->
                                        <img style="height:300, width:300" src="{{post.formatted_img_url}}" class="img-fluid" alt="...">
                                    </div>
                                    <div class="col-md-8">
                                        <h5 class="card-title">{{post.title}}</h5>
                                        <p class="card-text">{{post.content |truncatechars:45}}</p>
                                    <div class="d-flex justify-content-between">
                                        <a href="{% url 'blog:detail' slug=post.slug %}">Read More</a> <!--URL TAG-->
                                        <a class="text-decoration-none text-dark fw-bold" href="#">{{post.category.name}}</a>
                                    </div>
                                    <div class="d-flex justify-content-between mt-2" >
                                        {% if perms.blog.change_post %}
                                        <a class="btn btn-warning btn-sm" href="{% url 'blog:edit_post' post_id=post.id %}">Edit Post</a> <!--URL TAG-->
                                        {% endif %}
                                        <!--button used here bcoz here we cant delete just a click want to confirm once so using button and scripting it-->
                                        {% if perms.blog.delete_post %}
                                        <button class="btn btn-danger btn-sm" onclick="confirmBeforeDelete(`{% url 'blog:delete_post' post_id=post.id %}`)">Delete Post</button>
                                        {% endif %}
                                        <!--if post.is_published then -->
                                        {% if not post.is_published and perms.blog.can_publish %}
                                        <a href="{% url 'blog:publish_post' post_id=post.id %}" class="btn btn-success btn-sm">Publish</a>
                                        {% endif %}
                                                
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            {% endfor %} 
                <!---paginator coding-->
            <div class="col-12 my-3">
                <!---loop for other pages-->
                {% if page_obj.has_other_pages %}
                    <nav aria-label="Page navigation">
                        <ul class="pagination">
                            <!---paginator previous page-->
                            {% if page_obj.has_previous %}
                            <li class="page-item">
                                <a class="page-link" href="?page=1" aria-label="First">
                                    <span aria-hidden="true">&laquo; first</span>
                                </a>
                            </li>
                            <li class="page-item">
                                <!---paginator previous page-->
                                <a class="page-link" href="?page={{page_obj.previous_page_number}}" aria-label="Previous">
                                    <span aria-hidden="true">previous</span>
                                </a>
                            </li>
                            {% endif %}
                            <!---paginator -  pages(1 of 4) current pages of number of pages-->
                            <li class="page-item"><span class="page-link">Page {{page_obj.number}} of {{page_obj.paginator.num_pages}}.</span></li>
                            <!---paginator next page-->
                            {%if page_obj.has_next%}
                            <li class="page-item">
                                <a class="page-link" href="?page={{page_obj.next_page_number}}" aria-label="Next">
                                     <span aria-hidden="true">next</span>
                                </a>
                            </li>
                            <li class="page-item">
                            <!---paginator last page-->
                                <a class="page-link" href="?page={{page_obj.paginator.num_pages}}" aria-label="Last">
                                    <span aria-hidden="true">last &raquo;</span>
                                </a>
                            </li>
                            {% endif %}
                        </ul>
                    </nav>
                {% endif %}
            </div>
            {% else %}
                <p>No Posts Available</p>
            {% endif %}

        </div>
    </div>
    <!--script for ensuring for post delete -->
    <script>
        function confirmBeforeDelete(url) {
            var userConfirmed = confirm("Are you sure want to delete?")

            if (userConfirmed) {
                window.location.href = url
            }
        }
    </script>
{%endblock%}

blog/templates/blog/detail.html
    {% extends 'blog/base.html' %}

    {% block content %}
    <div class="container-fluid mb-5">
      <div class="row">
            <div class="col-lg-8">
              <h1 class="mb-4">{{post.title}} <small style="font-size:18px">({{post.category.name}})</small></h1>
              <!--post created_at date | date:for date format F-Month j=date Y=Year-->
              <p class="text-muted">Posted on: {{post.created_at | date:"F j, Y"}}</p>
              <!--post img_url-->
              <img src="{{post.formatted_img_url}}" class="img-fluid mb-4" alt="Blog Image">
              <p>{{post.content}}</p>
            </div>
      
            <div class="col-lg-4">
              <div class="card mt-3">
                <div class="card-body">
                  <h5 class="card-title">Related Posts</h5>
                  <ul class="list-unstyled">
                    {% for related_post in related_posts %}
                    <!--related post-->
                    <li><a href="{% url 'blog:detail' slug=related_post.slug %}">{{related_post.title}}</a></li>
                    {% endfor %}
                  </ul>
                </div>
              </div>
            </div>
        </div>
    </div>
    {% endblock %}

blog/templates/blog/forgot_password.html
{% extends 'blog/base.html' %}

{% block content %}
    <div class="container mt-5">
        <div class="row d-flex justify-content-center">
            <div class="col-3 mt-3">
                <h2>Forgot Password</h2>
                <div>
                    {% include 'blog/includes/errors.html' %}
                </div>
                <form method="post">
                    {% csrf_token %}
                    <div class="mb-3">
                        <label for="email" class="form-label">Email address</label>
                        <input type="email" class="form-control" id="email" name="email" required>
                    </div>
                    <button type="submit" class="btn btn-primary">Send Password Reset Email</button>
                </form>
            </div>
        </div>
    </div>
{% endblock %}

blog/templates/blog/index.html
{% extends 'blog/base.html' %}


{%block content %}
    <div class="container-fluid bg" style="background-image: url('C:\Users\910644\myapp\IMG\flower.avif');">
        <div class="row my-2">
            <div class="col">
                <h2 >{{blog_title | upper}}</h2> <!---filters-->
            </div>
            <div class="col-3">
                {% include 'blog/includes/errors.html'%}
                <div class="input-group">
                    <input type="text" class="form-control" placeholder="Search..." aria-label="Search">
                    <button class="btn btn-outline-light btn-primary " type="button" id="button-search">
                      <i class="bi bi-search"></i> <!-- Bootstrap Icons -->
                    </button>
                  </div>
            </div>
        </div>
        <div class="row mb-5">
            <!---loop through the paginator-->
            {% if page_obj %}
            <!---for through the paginator-->
                {% for post in page_obj %}
                    <div class="col-4 mb-4">
                        <div class="card">
                            <div class="card-body">
                                <div class="row">
                                    <div class="col-md-4">
                                        <!--post formatted img url -->
                                        <img style="height:300, width:300" src="{{post.formatted_img_url}}" class="img-fluid" alt="...">
                                    </div>
                                        <div class="col-md-8">
                                            <h5 class="card-title">{{post.title}}</h5>
                                            <p class="card-text">{{post.content |truncatechars:45}}</p>
                                                <div class="d-flex justify-content-between">
                                                    <a href="{% url 'blog:detail' slug=post.slug %}">Read More</a> <!--URL TAG-->
                                                    <a class="text-decoration-none text-dark fw-bold" href="#">{{post.category.name}}</a>
                                                </div>
                                        </div>
                                </div>
                            </div>
                        </div>
                    </div>
                {% endfor %} 
                <!---paginator coding-->
            <div class="col-12 my-3">
                <!---loop for other pages-->
                {% if page_obj.has_other_pages %}
                    <nav aria-label="Page navigation">
                        <ul class="pagination">
                            <!---paginator previous page-->
                            {% if page_obj.has_previous %}
                                <li class="page-item">
                                    <a class="page-link" href="?page=1" aria-label="First">
                                        <span aria-hidden="true">&laquo; first</span>
                                    </a>
                                </li>
                                <li class="page-item">
                                    <!---paginator previous page-->
                                    <a class="page-link" href="?page={{page_obj.previous_page_number}}" aria-label="Previous">
                                        <span aria-hidden="true">previous</span>
                                    </a>
                                </li>
                            {% endif %}
                            <!---paginator -  pages(1 of 4) current pages of number of pages-->
                                <li class="page-item"><span class="page-link">Page {{page_obj.number}} of {{page_obj.paginator.num_pages}}.</span></li>
                                <!---paginator next page-->
                                {%if page_obj.has_next%}
                                <li class="page-item">
                                    <a class="page-link" href="?page={{page_obj.next_page_number}}" aria-label="Next">
                                         <span aria-hidden="true">next</span>
                                    </a>
                                </li>
                                <li class="page-item">
                                    <!---paginator last page-->
                                    <a class="page-link" href="?page={{page_obj.paginator.num_pages}}" aria-label="Last">
                                        <span aria-hidden="true">last &raquo;</span>
                                    </a>
                                </li>
                                {% endif %}
                        </ul>
                    </nav>
                {% endif %}
            </div>
            {% else %}
            OOPs! No Post Available
            {% endif %}
         </div> 
          
    </div>

{% endblock %}

blog/templates/blog/login.html
{% extends "blog/base.html"%}

{% block content %}
    <div class="container-fluid">
        <div class="row d-flex justify-content-center mt-5">
            <div class="col-4">
                <h3>Login</h3>
                <div>
                  
                    {% include 'blog/includes/errors.html' %}
                
                </div>
        
                <div class="my-3">
                    <form method="post">
                        {% csrf_token %}
                        <div class="form-group">
                            <label for="username" class="form-label">Username</label>
                            <input type="text" class="form-control" id="username" name="username" value="{{form.username.value|default:""}}">
                        </div>
                       
                        <div class="form-group">
                            <label for="password" class="form-label">Password</label>
                            <input type="password" class="form-control" id="password" name="password">
                        </div>
                       
                        <div class="my-3 d-flex justify-content-between">
                            <!--added blog forgot password link-->
                            <a href="{% url 'blog:forgot_password' %}">Forgot Password</a>
                            <button type="submit" class="btn btn-primary">Login</button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>

{%endblock%}
    

blog/templates/blog/reset_password_email.html
<!--to convert variable as variable and other content as string otherwise it will consider variable also as string-->
<!--it prevent from hackers to generate or use the string as variable -->
{% autoescape off %}
Hello,

You requested a reset password for your account at {{domain}}.

Please click the link below to reset your password:

http://{{domain}}{% url 'blog:reset_password' uidb64=uid token=token %}

Thank you!
{% endautoescape %}